version: '3.4'

services:
  sso:
    image: ${DOCKER_REGISTRY-}sso
    build:
      context: .
      dockerfile: SSO/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:80"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - "5001:80"
    depends_on:
      - sso

volumes:
  postgres_data: {}
  redis_data: {}
