version: '3.4'

services:
  sso:
    image: ${DOCKER_REGISTRY-}sso
    build:
      context: .
      dockerfile: SSO/Dockerfile
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_secure_password
      POSTGRES_DB: my_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: api/Dockerfile

volumes:
  postgres_data: {}
  redis_data: {}


